// <auto-generated />
using System;
using IpsCitasMedicasBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IpsCitasMedicasBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250404025856_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IpsCitasMedicasBackend.Models.Cita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.ToTable("Citas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especialidad = "Medicina General",
                            Estado = "Disponible",
                            FechaHora = new DateTime(2025, 4, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Especialidad = "Odontología",
                            Estado = "Ocupado",
                            FechaHora = new DateTime(2025, 4, 6, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 2
                        },
                        new
                        {
                            Id = 3,
                            Especialidad = "Medicina General",
                            Estado = "Disponible",
                            FechaHora = new DateTime(2025, 4, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 3
                        },
                        new
                        {
                            Id = 4,
                            Especialidad = "Odontologia",
                            Estado = "Disponible",
                            FechaHora = new DateTime(2025, 4, 8, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            MedicoId = 4
                        });
                });

            modelBuilder.Entity("IpsCitasMedicasBackend.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especialidad = "Medicina General",
                            Nombre = "Dr. Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Especialidad = "Odontologia",
                            Nombre = "Dra. Ana Gómez"
                        },
                        new
                        {
                            Id = 3,
                            Especialidad = "Medicina General",
                            Nombre = "Dr. Luis Martínez"
                        },
                        new
                        {
                            Id = 4,
                            Especialidad = "Odontologia",
                            Nombre = "Dra. Camila López"
                        });
                });

            modelBuilder.Entity("IpsCitasMedicasBackend.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Ramírez",
                            Documento = "123456789",
                            FechaNacimiento = new DateTime(1995, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Carlos",
                            Telefono = "3001234567"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "Gómez",
                            Documento = "987654321",
                            FechaNacimiento = new DateTime(1988, 8, 15, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Laura",
                            Telefono = "3019876543"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "Fernández",
                            Documento = "1122334455",
                            FechaNacimiento = new DateTime(2000, 12, 25, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            Nombres = "Sofía",
                            Telefono = "3152223344"
                        });
                });

            modelBuilder.Entity("IpsCitasMedicasBackend.Models.Cita", b =>
                {
                    b.HasOne("IpsCitasMedicasBackend.Models.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });
#pragma warning restore 612, 618
        }
    }
}
